create database test2;
show databases;
use database test2;
create table test1(a int primary key, b long not null, c float primary key, d double, e string(10));
create table test2(a int primary key, b long not null, c float primary key, d double, e string(10));
create table test3(a int primary key, b long not null, c float primary key, d double, e string(10));
show table test1;
drop table test2;
show database test2;
drop database test2;
use database test;
drop database test2;
create table test1(a int primary key, b long not null, c float primary key, d double, e string(10));
insert into test1 values(1,1,1,1,'abc');
insert into test1 (a,b,c) values(0,0,0);
insert into test1 (a,c,d,e) values(2,2,2,'abc');
insert into test1 (b,c,d,e) values(1,1,1,'abc');
insert into test1 values (1,1,1,1,'abc');
insert into test1 values (3,1,1,1,'abc');
insert into test1 values (1,1,3,1,'abc');
--insert into test1 values(2,2,2,2,'abcabcabcabc');
insert into test1 values (2,2,2,2,'abc'),(3,3,3,3,'abc'),(4,4,4,4,'abc'),(5,5,5,5,'def'),(6,6,6,6,'def');
--select * from test1;
select a+2, b*3, (b+c)*a, d/2 from test1;
select * from test1 where (a < 3 OR b >=4) AND (e <> 'def' OR d=6);
create table test2(a int primary key, b long, c float, d double, e string(10));
create table test3(a int primary key, b long, c float, d double, e string(10));
drop table test1;
drop table test2;
drop table test3;
quit